server:
  port: 80

spring:
  application:
    name: cloud-order-service


eureka:
  client:
    register-with-eureka: true  #是否向注册中心注册自己
    fetch-registry: true  #是否向注册中心抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://127.0.0.1:7001/eureka 单机版
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka #集群版