server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.135:8848


#消费者将要去访问的微服务(成功注册进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-payment-provider