server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.6.135:8848
    sentinel:
      transport:
        dashboard: 192.168.6.135:8080 #配置sentinel dashboard地址
        port: 8719  #默认8719端口，加入被占用会自动从8719一次+1扫描，直到找到未被占用的端口
        client-ip: 172.23.41.38
      datasource: #sentinel 持久化
        ds1:
          nacos:
            serverAddr: 192.168.6.135:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            dataType: json
            ruleType: flow


management:
  endpoints:
    web:
      exposure:
        include: '*'