server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh     #路由的ID，没有固定规则但要求统一，建议配合服务名
          #uri: http://127.0.0.1:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/**    #断言，路径相匹配的进行路由
            #- After=2020-11-23T16:53:41.961+08:00[Asia/Shanghai] #在当前时间之后
            #- Cookie=username,hawk #携带cookie
            #- Header=X-request-Id,\d+   #请求头要有X-Request-Id属性并且值为正数的
            #- Method=GET   #请求方式


eureka:
  instance:
    instance-id: cloud-gateway-service
  client:
    register-with-eureka: true  #是否向注册中心注册自己
    fetch-registry: true  #是否向注册中心抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://127.0.0.1:7001/eureka 单机版
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka #集群版