server:
  port: 80

spring:
  application:
    name: cloud-order-service


eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
  client:
    register-with-eureka: true  #是否向注册中心注册自己
    fetch-registry: true  #是否向注册中心抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://127.0.0.1:7001/eureka 单机版
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka #集群版

# 设置feign客户端超时时间(openfeign默认支持ribbon)
#ribbon:
#  ReadTimeout: 5000
#  ConnectTimeout: 5000

# feign日志配置
#logging:
#  level:
#    com.naokeziteng.cloud.service.PaymentFeignService: debug

# 开启服务降级
feign:
  hystrix:
    enabled: true