server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于和binding整合
          type: rabbit  #消息组件类型
          environment: #设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.6.135
                port: 5672
                username: hawk
                password: hawk
      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的Exchange名称定义
          content-type: application/json  #设置消息类型，本次为json，文本则设置为'text/plain'
          binder: defaultRabbit #设置要绑定的消息服务的具体配置
          group: hawk


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8802