server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
  client:
    register-with-eureka: true  #是否向注册中心注册自己
    fetch-registry: true  #是否向注册中心抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka